In [54]:
import torch
from tensorly.tenalg import khatri_rao

In [ ]:
torch.repea

In [43]:
A = torch.arange(0, 3).unsqueeze(1) + torch.arange(4)
B = torch.arange(2, 5).unsqueeze(1) + torch.arange(4)

In [64]:
C1 = torch.einsum("ik,jk->ijk", [A, B])
C2 = C1.reshape(A.shape[0] * B.shape[0], -1)

In [74]:
x = torch.arange(24.0).reshape((3, 4, 2))

In [76]:
x[..., 0]

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.]])

In [82]:
x[:, 1, 0]

tensor([ 2., 10., 18.])

In [77]:
x.reshape(x.shape[0], -1)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20., 21., 22., 23.]])

In [72]:
A.reshape(2, -1)

tensor([[0, 1, 2, 3, 1, 2],
        [3, 4, 2, 3, 4, 5]])

In [ ]:
C1.reshape(-1, C1.shape[-1a]).shape

torch.Size([9, 4])

In [63]:
A.shape

torch.Size([3, 4])

In [70]:
khatri_rao([A, B]).shape

torch.Size([9, 4])

In [53]:
C

tensor([[ 0,  3,  8, 15],
        [ 0,  4, 10, 18],
        [ 0,  5, 12, 21],
        [ 2,  6, 12, 20],
        [ 3,  8, 15, 24],
        [ 4, 10, 18, 28],
        [ 4,  9, 16, 25],
        [ 6, 12, 20, 30],
        [ 8, 15, 24, 35]])